from __future__ import annotations

from dataclasses import dataclass
from itertools import combinations
from typing import Iterable, Sequence

import torch
from torch import nn
from torch.nn import functional as F

from rtv_solver.pipeline.model_simpleScoring import ScoringMLP
from rtv_solver.structure.trip_cost import TripCost


@dataclass(frozen=True)
class CandidateGraph:
    """
    Graph representation for one rolling-horizon iteration.

    Node ordering is identical to the score-vector ordering expected by the
    existing COAML pipeline:

        [trip candidates..., reject actions...]

    This invariant is essential. The neural-network output, ILP variables,
    imitation-learning target and later SRL action masks must all refer to the
    same candidate at every index.
    """

    edge_index: torch.Tensor
    vehicle_ids: tuple[int, ...]
    request_ids: tuple[frozenset[int], ...]
    is_reject: tuple[bool, ...]

    @property
    def num_nodes(self) -> int:
        return len(self.vehicle_ids)


class CandidateConflictGraphBuilder:
    """
    Build the Version-B conflict graph over RTV candidates.

    Nodes
    -----
    One node per normal vehicle-trip candidate, followed by one node per
    vehicle-specific reject action.

    Edges
    -----
    Two nodes are connected when the corresponding actions compete because:

    1. they belong to the same vehicle, or
    2. they contain at least one common request.

    The returned graph is undirected, represented by two directed edges for
    every undirected relation. Duplicate edges are removed.

    Reject nodes contain no requests. They are connected to all normal
    candidates of the same vehicle, because a vehicle cannot simultaneously
    reject and select a normal trip.

    # REVIEW (2026-07-30, feedback only - not yet changed):
    # Not wired into coaml_pipeline.py yet. solve_iteration() calls
    # `self.model(feature_tensor_with_reject)` with ONE positional arg (see
    # coaml_pipeline.py:588 and the `scores = self.model(feature_tensor)` call
    # inside _compute_fy_loss_from_optimal_solution) - neither call site builds
    # a CandidateGraph or passes edge_index. `requires_graph = True` on
    # CandidateScoringGNN below is a good hook for branching on this, but the
    # actual `if getattr(self.model, "requires_graph", False): ...` branch
    # doesn't exist yet in coaml_pipeline.py.
    # Still need to check (haven't yet): does FenchelYoungLoss's MAP-oracle
    # perturbation re-invoke self.model internally for the perturbed samples,
    # or does it only perturb/re-solve over the already-computed `scores`
    # tensor? If it re-invokes the model, edge_index needs to be threaded
    # through make_map_oracle too, not just the one `scores = self.model(...)`
    # call site.
    """

    def build(
        self,
        trip_costs: Sequence[TripCost],
        reject_vehicle_ids: Sequence[int],
        *,
        device: torch.device | str | None = None,
    ) -> CandidateGraph:
        vehicle_ids: list[int] = []
        request_ids: list[frozenset[int]] = []
        is_reject: list[bool] = []

        # Normal candidate nodes must remain in exactly the same order as
        # trip_costs and the feature matrix generated by FeatureBuilder.
        for trip_cost in trip_costs:
            vehicle_ids.append(int(trip_cost.vehicle_id))
            request_ids.append(self._extract_request_ids(trip_cost))
            is_reject.append(False)

        # Reject nodes are appended in exactly the same order used by
        # FeatureBuilder.add_reject_action_entries().
        for vehicle_id in reject_vehicle_ids:
            vehicle_ids.append(int(vehicle_id))
            request_ids.append(frozenset())
            is_reject.append(True)

        edge_pairs: set[tuple[int, int]] = set()

        # Candidates assigned to the same vehicle compete with one another.
        nodes_by_vehicle: dict[int, list[int]] = {}
        for node_idx, vehicle_id in enumerate(vehicle_ids):
            nodes_by_vehicle.setdefault(vehicle_id, []).append(node_idx)

        for node_indices in nodes_by_vehicle.values():
            self._connect_clique(node_indices, edge_pairs)

        # Candidates containing the same request compete across vehicles.
        # REVIEW (2026-07-30): both clique loops here are O(k^2) edges per
        # vehicle/request group. Fine for small Li&Lim class-1 batches, but a
        # vehicle or request with many feasible candidates (larger NYC-style
        # batches, higher max_cardinality) could blow up edge count quickly -
        # e.g. one request reachable by 50 vehicles = 50*49 directed edges from
        # that one request alone. Worth a top-k cap or sparsification pass
        # before testing on anything beyond the current small-instance scale.
        nodes_by_request: dict[int, list[int]] = {}
        for node_idx, candidate_request_ids in enumerate(request_ids):
            for request_id in candidate_request_ids:
                nodes_by_request.setdefault(request_id, []).append(node_idx)

        for node_indices in nodes_by_request.values():
            self._connect_clique(node_indices, edge_pairs)

        if edge_pairs:
            ordered_edges = sorted(edge_pairs)
            edge_index = torch.tensor(
                ordered_edges,
                dtype=torch.long,
                device=device,
            ).t().contiguous()
        else:
            edge_index = torch.empty(
                (2, 0),
                dtype=torch.long,
                device=device,
            )

        graph = CandidateGraph(
            edge_index=edge_index,
            vehicle_ids=tuple(vehicle_ids),
            request_ids=tuple(request_ids),
            is_reject=tuple(is_reject),
        )
        self._validate(graph, len(trip_costs), len(reject_vehicle_ids))
        return graph

    @staticmethod
    def _extract_request_ids(trip_cost: TripCost) -> frozenset[int]:
        """
        Extract all request ids represented by one vehicle-trip candidate.

        TripInsertionPlan.trips is expected to contain the underlying
        single-request Trip objects. The explicit validation avoids silently
        constructing an incorrect graph when this assumption changes.

        # REVIEW (2026-07-30): cross-checked against feat_builder.py's
        # _trip_cost_features, which already sums am/wc capacity "across all
        # trips in the plan" via the same `plan.trips` attribute for shared
        # (multi-request) trips - so this reuses the same source of truth the
        # rest of the codebase already relies on for shared-trip request
        # breakdown. Looks consistent, but hasn't been exercised against a real
        # cardinality>=2 SharedTrip candidate in this review - worth confirming
        # with an actual multi-request TripCost in the test script.
        """
        plan = getattr(trip_cost, "plan", None)
        plan_trips = getattr(plan, "trips", None)

        if plan_trips is None:
            raise ValueError(
                "TripCost.plan.trips is required to build candidate conflicts."
            )

        extracted_ids: set[int] = set()
        for trip in plan_trips:
            request_id = getattr(trip, "request_id", None)
            if request_id is None:
                raise ValueError(
                    "Every element of TripCost.plan.trips must expose request_id."
                )
            extracted_ids.add(int(request_id))

        return frozenset(extracted_ids)

    @staticmethod
    def _connect_clique(
        node_indices: Iterable[int],
        edge_pairs: set[tuple[int, int]],
    ) -> None:
        """
        Connect every pair in both directions.

        Message passing libraries commonly represent undirected graphs as two
        directed edges. Self-loops are handled inside the GNN layer through a
        separate self transformation and are therefore not added here.
        """
        unique_indices = sorted(set(node_indices))
        for left, right in combinations(unique_indices, 2):
            edge_pairs.add((left, right))
            edge_pairs.add((right, left))

    @staticmethod
    def _validate(
        graph: CandidateGraph,
        num_trip_candidates: int,
        num_reject_actions: int,
    ) -> None:
        expected_nodes = num_trip_candidates + num_reject_actions
        if graph.num_nodes != expected_nodes:
            raise ValueError(
                f"Candidate graph contains {graph.num_nodes} nodes, "
                f"expected {expected_nodes}."
            )

        if graph.edge_index.ndim != 2 or graph.edge_index.shape[0] != 2:
            raise ValueError("edge_index must have shape [2, num_edges].")

        if graph.edge_index.numel() > 0:
            min_index = int(graph.edge_index.min().item())
            max_index = int(graph.edge_index.max().item())
            if min_index < 0 or max_index >= expected_nodes:
                raise ValueError(
                    "edge_index contains a node index outside the candidate range."
                )


class MeanGraphSAGELayer(nn.Module):
    """
    Minimal mean-aggregation GraphSAGE layer implemented in plain PyTorch.

    For every node, the layer combines:
    - a transformation of its own representation, and
    - a transformation of the mean representation of its conflict neighbours.

    A custom implementation keeps the first prototype independent of
    torch-geometric and makes the message-passing operation transparent.

    # REVIEW (2026-07-30): single homogeneous edge type - "same vehicle" and
    # "same request" conflicts are mixed into the same mean-aggregation. These
    # are structurally different kinds of competition (own alternative trip vs.
    # another vehicle taking your passenger); a relational/heterogeneous
    # variant (separate weight matrix per edge type, R-GCN style) might let the
    # model distinguish them instead of averaging both into one signal. Not
    # required for a first correctness test, but a natural next iteration.
    """

    def __init__(self, hidden_dim: int, dropout: float = 0.0) -> None:
        super().__init__()
        self.self_linear = nn.Linear(hidden_dim, hidden_dim)
        self.neighbour_linear = nn.Linear(hidden_dim, hidden_dim, bias=False)
        self.layer_norm = nn.LayerNorm(hidden_dim)
        self.dropout = nn.Dropout(dropout)

    def forward(
        self,
        node_embeddings: torch.Tensor,
        edge_index: torch.Tensor,
    ) -> torch.Tensor:
        if node_embeddings.ndim != 2:
            raise ValueError(
                "node_embeddings must have shape [num_nodes, hidden_dim]."
            )
        if edge_index.ndim != 2 or edge_index.shape[0] != 2:
            raise ValueError("edge_index must have shape [2, num_edges].")

        num_nodes, hidden_dim = node_embeddings.shape
        neighbour_sum = node_embeddings.new_zeros((num_nodes, hidden_dim))
        neighbour_count = node_embeddings.new_zeros((num_nodes, 1))

        if edge_index.numel() > 0:
            source_nodes = edge_index[0]
            target_nodes = edge_index[1]

            neighbour_sum.index_add_(
                0,
                target_nodes,
                node_embeddings[source_nodes],
            )
            neighbour_count.index_add_(
                0,
                target_nodes,
                torch.ones(
                    (target_nodes.shape[0], 1),
                    dtype=node_embeddings.dtype,
                    device=node_embeddings.device,
                ),
            )

        mean_neighbours = neighbour_sum / neighbour_count.clamp_min(1.0)

        updated = (
            self.self_linear(node_embeddings)
            + self.neighbour_linear(mean_neighbours)
        )
        updated = F.relu(updated)
        updated = self.dropout(updated)

        # The residual connection preserves the candidate's own information
        # even when it has many competing neighbours.
        return self.layer_norm(node_embeddings + updated)


class CandidateScoringGNN(nn.Module):
    """
    Score all RTV candidates jointly using the Version-B conflict graph.

    The model deliberately has the same external output as ScoringMLP:
    one unrestricted scalar score per input row. It does not contain any SIL-
    or SRL-specific loss logic and can therefore serve as the actor's scoring
    network in both training paradigms.

    Pipeline
    --------
    candidate features
        -> feature encoder
        -> conflict-aware message passing
        -> scalar score head

    No sigmoid or softmax is applied because the existing ILP and
    Fenchel-Young loss operate on unrestricted utility scores.

    # REVIEW (2026-07-30, overall assessment - feedback only, nothing changed):
    # Architecture fits well: output interface matches ScoringMLP exactly (one
    # scalar per row, no activation), and feature_dim is a plain constructor
    # arg - so this can be tested with the CURRENT feat_builder.py's 84-dim
    # features first, then swapped to feat_builder_new.py's 87-dim features
    # later without touching this file. Good separation of concerns: conflict
    # structure lives in edges (CandidateGraph), not stuffed into node
    # features - matches the "GNN-specific conflict info as edges, not mixed
    # into features" principle from the earlier feature-cleanup review.
    #
    # Main open items before wiring into training (see other REVIEW comments
    # above for detail):
    # 1. Not yet called from coaml_pipeline.py - both self.model(...) call
    #    sites need a CandidateGraph built and edge_index passed through, and
    #    FenchelYoungLoss/make_map_oracle need checking for whether they
    #    re-invoke the model internally.
    # 2. Clique-based edges could blow up on larger batches (NYC-scale) -
    #    fine for the current small Li&Lim class-1 test scope.
    # 3. num_message_passing_layers defaults to 1 (only 1-hop conflict
    #    propagation) - worth trying 2 once the pipeline runs end-to-end.
    # 4. Single homogeneous edge type mixing two different conflict kinds
    #    (see MeanGraphSAGELayer review above).
    #
    # Next step (as requested): a standalone test script exercising
    # CandidateConflictGraphBuilder + CandidateScoringGNN against real
    # trip_costs/reject_vehicle_ids from a small instance, using the CURRENT
    # FeatureBuilder (84-dim) - checking node order/count, that same-vehicle
    # and same-request candidates actually get connected, and a NaN-free
    # forward pass. No pipeline wiring yet.
    """

    requires_graph = True

    def __init__(
        self,
        feature_dim: int,
        hidden_dim: int,
        *,
        num_message_passing_layers: int = 1,
        dropout: float = 0.0,
    ) -> None:
        super().__init__()

        if feature_dim <= 0:
            raise ValueError("feature_dim must be positive.")
        if hidden_dim <= 0:
            raise ValueError("hidden_dim must be positive.")
        if num_message_passing_layers < 1:
            raise ValueError(
                "num_message_passing_layers must be at least one."
            )

        self.feature_dim = feature_dim
        self.hidden_dim = hidden_dim
        self.num_message_passing_layers = num_message_passing_layers

        self.encoder = nn.Sequential(
            nn.Linear(feature_dim, hidden_dim),
            nn.ReLU(),
            nn.LayerNorm(hidden_dim),
        )

        self.message_passing_layers = nn.ModuleList(
            MeanGraphSAGELayer(hidden_dim, dropout=dropout)
            for _ in range(num_message_passing_layers)
        )

        self.score_head = nn.Linear(hidden_dim, 1)

    def forward(
        self,
        candidate_features: torch.Tensor,
        edge_index: torch.Tensor,
        *,
        return_embeddings: bool = False,
    ) -> torch.Tensor | tuple[torch.Tensor, torch.Tensor]:
        if candidate_features.ndim != 2:
            raise ValueError(
                "candidate_features must have shape [num_candidates, feature_dim]."
            )
        if candidate_features.shape[1] != self.feature_dim:
            raise ValueError(
                f"Expected {self.feature_dim} input features, "
                f"received {candidate_features.shape[1]}."
            )

        # Keep graph tensors on the same device as the candidate features.
        edge_index = edge_index.to(candidate_features.device)

        embeddings = self.encoder(candidate_features)
        for layer in self.message_passing_layers:
            embeddings = layer(embeddings, edge_index)

        scores = self.score_head(embeddings).squeeze(-1)

        if scores.shape[0] != candidate_features.shape[0]:
            raise RuntimeError(
                "The GNN must return exactly one score per candidate node."
            )

        if return_embeddings:
            # The embeddings can later be reused as critic input in SRL without
            # changing the actor's normal scoring interface.
            return scores, embeddings

        return scores


def build_scoring_model(
    model_type: str,
    feature_dim: int,
    hidden_dim: int,
    *,
    num_message_passing_layers: int = 1,
) -> nn.Module:
    """
    Factory for the trip-scoring model, additive alongside plain ScoringMLP
    construction so training_loop.py/coaml_pipeline.py can build either model
    from Config.MODEL_TYPE without duplicating the branch in both places.
    Does not change or remove the ScoringMLP path - "mlp" stays the default.
    """
    if model_type == "mlp":
        return ScoringMLP(feature_dim=feature_dim, hidden_dim=hidden_dim)
    if model_type == "gnn":
        return CandidateScoringGNN(
            feature_dim=feature_dim,
            hidden_dim=hidden_dim,
            num_message_passing_layers=num_message_passing_layers,
        )
    raise ValueError(f"Unknown model_type: {model_type!r} (expected 'mlp' or 'gnn').")
