name: coaml

channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  - python=3.10
  - pytorch
  - numpy
  - matplotlib
  - pandas
  - networkx
  - pillow
  - folium
  - geopy
  - ipython
  - ipykernel
  - jupyter_client
  - pytest
  - pytest-mock
  - sympy
  - pip

  - pip:
      - certifi
      - gurobipy==10.0.3
      - hexaly==14.5.20260220
      - numpy==1.26.0
      - pandas==2.3.3
      - python-dateutil
      - pytz
      - requests
      - tzdata
      - urllib3