#!/bin/bash
#SBATCH -J rtv-coaml-offline            # Job name
#SBATCH -o /home/jiw42/slurm_logs/exp_%x_%j.out             # output file (%j expands to jobID)
#SBATCH -e /home/jiw42/slurm_logs/exp_%x_%j.err             # error log file (%j expands to jobID)
#SBATCH --mail-type=ALL                 # Request status by email 
#SBATCH --mail-user=jiw42@cornell.edu   # Email address to send results to.
#SBATCH -N 1                            # Total number of nodes requested
#SBATCH -n 128                          # Total number of cores requested
#SBATCH --get-user-env                  # retrieve the users login environment
#SBATCH --mem=200000                    # server memory requested (per node)
#SBATCH -t 12:00:00                     # Time limit (hh:mm:ss)
#SBATCH --partition=samitha             # Request partition

echo "Starting job $SLURM_JOB_ID"

### PATHS ###
REPO_ROOT=$HOME/rtv-solver
PYTHON=$HOME/.conda/envs/coaml/bin/python

INPUT_FILE="solutions/li_lim/manifests/lc101.json"
IMITATION_SOLUTION_FILE="$INPUT_FILE"

### EXPERIMENT PARAMETERS (from run_main.sh)
OUTPUT_DIR_NAME="experiments"
MAX_THREAD_CNT=128
RTV_TIMEOUT=3600
ILP_TIMEOUT=120
ILP_PENALTY=100000
MAX_CARDINALITY=3
LARGEST_TSP=16
SHARE_COST_FACTOR=5
STEP_SIZE=100
BATCH_INTERVAL=400
SEED=42
MODE=offline
EPOCHS=1
LEARNING_RATE=5e-3

export GRB_LICENSE_FILE="$HOME/gurobi_web.lic"
ulimit -c unlimited

echo "Python used:"
which python
python -c "import rtv_solver; print(rtv_solver.__file__)"

cd $REPO_ROOT
$PYTHON rtv_solver/main.py \
  --input_file $INPUT_FILE \
  --imitation_solution_file $IMITATION_SOLUTION_FILE \
  --output_dir $OUTPUT_DIR_NAME \
  --max_thread_cnt $MAX_THREAD_CNT \
  --rtv_timeout $RTV_TIMEOUT \
  --ilp_timeout $ILP_TIMEOUT \
  --ilp_penalty $ILP_PENALTY \
  --max_cardinality $MAX_CARDINALITY \
  --largest_tsp $LARGEST_TSP \
  --share_cost_factor $SHARE_COST_FACTOR \
  --step_size $STEP_SIZE \
  --batch_interval $BATCH_INTERVAL \
  --seed $SEED \
  --mode $MODE \
  --epochs $EPOCHS \
  --learning_rate $LEARNING_RATE 

echo "Job $SLURM_JOB_ID completed"

