#!/bin/bash
#SBATCH -J rtv-offline           # Job name
#SBATCH -o /home/jiw42/slurm_logs/exp_%x_%A_%a.out
#SBATCH -e /home/jiw42/slurm_logs/exp_%x_%A_%a.err
#SBATCH --mail-type=END,FAIL                 # Request status by email 
#SBATCH --mail-user=jiw42@cornell.edu   # Email address to send results to.
#SBATCH -N 1                            # Total number of nodes requested
#SBATCH -n 32                          # Total number of cores requested
#SBATCH --get-user-env                  # retrieve the users login environment
#SBATCH --mem=32000                    # server memory requested (per node)
#SBATCH -t 12:00:00                     # Time limit (hh:mm:ss)
#SBATCH --partition=samitha             # Request partition
#SBATCH --array=0-55         # 56 jobs

echo "Starting job $SLURM_ARRAY_JOB_ID, task $SLURM_ARRAY_TASK_ID"

### PATHS ###
REPO_ROOT=$HOME/rtv-solver
PYTHON=$HOME/.conda/envs/coaml/bin/python

INPUT_FILES=( \
lc101 lc102 lc103 lc104 lc105 lc106 lc107 lc108 lc109 \
lc201 lc202 lc203 lc204 lc205 lc206 lc207 lc208 \
lr101 lr102 lr103 lr104 lr105 lr106 lr107 lr108 lr109 lr110 lr111 lr112 \
lr201 lr202 lr203 lr204 lr205 lr206 lr207 lr208 lr209 lr210 lr211 \
lrc101 lrc102 lrc103 lrc104 lrc105 lrc106 lrc107 lrc108 \
lrc201 lrc202 lrc203 lrc204 lrc205 lrc206 lrc207 lrc208 \
)
INPUT_FILE_NAME=${INPUT_FILES[$SLURM_ARRAY_TASK_ID]}

INPUT_FILE="solutions/li_lim/manifests/$INPUT_FILE_NAME.json"
IMITATION_SOLUTION_FILE="$INPUT_FILE"

### EXPERIMENT PARAMETERS (from run_main.sh)
# offline missing is 100-200 with Card3
OUTPUT_DIR_NAME="experiments"
MAX_THREAD_CNT=32
MAX_CARDINALITY=4
STEP_SIZE=100
BATCH_INTERVAL=200
SEED=42
MODE="offline"

export GRB_LICENSE_FILE="$HOME/gurobi.lic"
ulimit -c unlimited

echo "Python used:"
which python
python -c "import rtv_solver; print(rtv_solver.__file__)"

cd $REPO_ROOT
$PYTHON rtv_solver/main.py \
  --input_file $INPUT_FILE \
  --imitation_solution_file $IMITATION_SOLUTION_FILE \
  --output_dir $OUTPUT_DIR_NAME \
  --max_thread_cnt $MAX_THREAD_CNT \
  --max_cardinality $MAX_CARDINALITY \
  --step_size $STEP_SIZE \
  --batch_interval $BATCH_INTERVAL \
  --seed $SEED \
  --mode $MODE

echo "Job $SLURM_JOB_ID completed"