#!/bin/bash
#SBATCH -J cluster_test            # Job name
#SBATCH -o /home/jiw42/slurm_logs/exp_%x_%j.out             # output file (%j expands to jobID)
#SBATCH -e /home/jiw42/slurm_logs/exp_%x_%j.err             # error log file (%j expands to jobID)
#SBATCH --mail-type=ALL                 # Request status by email 
#SBATCH --mail-user=jiw42@cornell.edu   # Email address to send results to.
#SBATCH -N 1                            # Total number of nodes requested
#SBATCH -n 128                          # Total number of cores requested
#SBATCH --get-user-env                  # retrieve the users login environment
#SBATCH --mem=200000                    # server memory requested (per node)
#SBATCH -t 12:00:00                     # Time limit (hh:mm:ss)
#SBATCH --partition=samitha             # Request partition

echo "Starting job $SLURM_JOB_ID"

REPO_ROOT=$HOME/rtv-solver
PYTHON=$HOME/.conda/envs/coaml/bin/python

cd $REPO_ROOT

export GRB_LICENSE_FILE=$HOME/gurobi_web.lic

ulimit -c unlimited

$PYTHON rtv_solver/main.py \
  --input_file $INPUT_FILE \
  --max_cardinality $MAX_CARIDINALITY \
  --mode $MODE \
  --batch_interval $BATCH_INTERVAL \
  --step_size $STEP_SIZE

