#!/bin/bash
#SBATCH -J rtv-coaml-offline            # Job name
#SBATCH -o /home/jiw42/slurm_logs/exp_%x_%j.out             # output file (%j expands to jobID)
#SBATCH -e /home/jiw42/slurm_logs/exp_%x_%j.err             # error log file (%j expands to jobID)
#SBATCH --mail-type=ALL                 # Request status by email 
#SBATCH --mail-user=jiw42@cornell.edu   # Email address to send results to.
#SBATCH -N 1                            # Total number of nodes requested
#SBATCH -n 32                          # Total number of cores requested
#SBATCH --get-user-env                  # retrieve the users login environment
#SBATCH --mem=32000                   # server memory requested (per node)
#SBATCH -t 16:00:00                     # Time limit (hh:mm:ss)
#SBATCH -p samitha

echo "Starting job $SLURM_JOB_ID"

### PATHS ###
REPO_ROOT=$HOME/rtv-solver
PYTHON=$HOME/.conda/envs/coaml/bin/python

INPUT_DIR="solutions/li_lim/manifests"

### EXPERIMENT PARAMETERS (from run_main.sh)
OUTPUT_DIR_NAME="experiments"
MAX_THREAD_CNT=32
MAX_CARDINALITY=3
STEP_SIZE=100
BATCH_INTERVAL=400
SEED=42
MODE="coaml"
EPOCHS=5
LEARNING_RATE=1e-4


export GRB_LICENSE_FILE="$HOME/gurobi.lic"
ulimit -c unlimited

echo "Python used:"
which python
python -c "import rtv_solver; print(rtv_solver.__file__)"

cd $REPO_ROOT
$PYTHON rtv_solver/main.py \
  --input_dir $INPUT_DIR \
  --output_dir $OUTPUT_DIR_NAME \
  --max_thread_cnt $MAX_THREAD_CNT \
  --max_cardinality $MAX_CARDINALITY \
  --step_size $STEP_SIZE \
  --batch_interval $BATCH_INTERVAL \
  --seed $SEED \
  --mode $MODE \
  --epochs $EPOCHS \
  --learning_rate $LEARNING_RATE 

echo "Job $SLURM_JOB_ID completed"

