#!/bin/bash
#SBATCH -J rtv-coaml                    # Job name
#SBATCH -o test_file_%j.out             # output file (%j expands to jobID)
#SBATCH -e test_file_%j.err             # error log file (%j expands to jobID)
#SBATCH --mail-type=ALL                 # Request status by email 
#SBATCH --mail-user=NETID@cornell.edu   # Email address to send results to.
#SBATCH -N 1                            # Total number of nodes requested
#SBATCH -n 128                          # Total number of cores requested
#SBATCH --get-user-env                  # retrieve the users login environment
#SBATCH --mem=200000                    # server memory requested (per node)
#SBATCH -t 12:00:00                     # Time limit (hh:mm:ss)
#SBATCH --partition=samitha             # Request partition

## parameter arguments for experiment
GRB_LICENSE_FILE=../../gurobi_web.lic
BATCH_INTERVAL=1600
STEP_SIZE=800
RTV_TIMEOUT=30000
ILP_TIMEOUT=120
INITIAL_TIME=60000
FINAL_TIME=100000
INPUT_FILE="wilson_nc_initial.pkl" # stored in rtv_solver/inputs/
## dynamic output directory / partially also implemented inside the code but can be overwritten here
OUTPUT_DIR="outputs/$city/integrated3/$no_veh/$veh_cap/INT_30_RV_0_RR_30_limit_5_min_pen_10_GRB_20_RTV_30/"

ulimit -c unlimited
mkdir -p "$OUTPUT_DIR"
source ~/coaml/bin/activate
python main.py \
  --max_cardinality 3 \
  --mode online \
  --batch_interval 3600 \
  --step_size 1200

